### ISSUE TITLE
How to run with HTTP client support?

### ISSUE THREAD

**Issue by anderspitman** [extism/js-sdk#101]
I'm trying to run this example with the JS SDK: https://github.com/extism/rust-pdk/blob/main/examples/http.rs

Looking through the code it appears HTTP functionality is implemented, but I'm getting this error: 

```
Error: from module "main": cannot resolve import "extism:host/env" "http_headers" ("extism:host/env" is a host module, but does not contain "http_headers")
```

Any tips on what I'm doing wrong?

**Comment by bhelx** [comment]
This is a feature we recently added I believe. Which version of the js-sdk are you using? It may be out of date. I think @chrisdickinson or @zshipko should be able to help.

**Comment by chrisdickinson** [comment]
I believe we support it on `main` but we haven't published a new release yet. There are some issues with Deno 2 that need to be worked through first – I believe the Deno 2 _build_ issues are resolved as of #100, but we had to disable WASIp1 support to get there. Cutting a new release of the `js-sdk` is on my radar this week.

**Comment by bhelx** [comment]
So, I think @anderspitman can point npm at github `main` for the time being?

**Comment by chrisdickinson** [comment]
Unfortunately no – the SDK requires a build step to produce a usable artifact. We'll need to cut a release.

**Comment by chrisdickinson** [comment]
Just released `v2.0.0-rc10` to npm and jsr – that should include the `http_headers` changes!

**Comment by anderspitman** [comment]
Thanks for the quick turnaround! I continue to be impressed by this project.

Definitely closer with 2.0.0-rc10:

```
http_request is not enabled
http_status_code is not enabled
http_headers is not enabled
```

What's the proper way to enable those?

**Comment by chrisdickinson** [comment]
Ha, you beat me to the punch, I was just typing that! :smile:

**Comment by anderspitman** [comment]
It's working in Node. You said above there's still some issues for Deno 2. I'm getting the following:

```
Uncaught (in promise) Error: Cannot enable off-thread wasm; current context is not `crossOriginIsolated`
```

Is this expected?

**Comment by chrisdickinson** [comment]
That's a new one – `runInWorker` _should_ work in Deno 2. (That looks like it's picking up the browser version of the package; are you installing using JSR?)

**Comment by chrisdickinson** [comment]
I was able to run the following successfully using a worker on deno 2.0.6 (after running `deno add jsr:@extism/extism@2.0.0-rc10`):

```ts
import { createPlugin } from '@extism/extism'

const plugin = await createPlugin('https://github.com/extism/extism/raw/refs/heads/main/wasm/http.wasm', { runInWorker: true, allowedHosts: ['*'] })
console.log((await plugin.call('http_request', JSON.stringify({ url: 'https://www.neversaw.us/', headers: {} }))).text())
```

**Comment by anderspitman** [comment]
That did it. Previously I was using this jsdelivr URL: https://cdn.jsdelivr.net/npm/@extism/extism@2.0.0-rc10/+esm

Do you happen to know what JSR is doing differently. In any case, it's working now.

Thanks for all your help! Can't wait to get my plugin fleshed out.

**Comment by chrisdickinson** [comment]
No problem at all – thanks for your patience working through the issues :smile: JSR packages the original source for Deno (v2) to consume; Deno v1 used to be able to use the github urls directly. JSDelivr is –I bet– picking up on the multi-target npm build we provide and selecting the "browser" distribution. (The Extism npm package provides individual builds for node commonjs, ESM, and browsers!)

**Comment by bbb0ttle** [comment]
Hello, my package version is 2.0.0-rc11, after set `runInWorker` to `true`, i got the error  in web browser console:
```
mod.ts:125 Uncaught (in promise) Error: Cannot enable off-thread wasm; current context is not `crossOriginIsolated` (see https://mdn.io/crossOriginIsolated)
```
