### ISSUE TITLE
Propose changing sample wasm URL to avoid CORS block

### ISSUE THREAD

**Issue by bradyjoslin** [extism/js-sdk#104]
For those targeting the browser, [this example](https://github.com/extism/js-sdk/blob/269384709e442fbdcd425e9a093c558aa62dbebe/README.md?plain=1#L64):

```js
const plugin = await createPlugin(
    'https://github.com/extism/plugins/releases/latest/download/count_vowels.wasm',
    { useWasi: true }
);
```
fails due to CORS.  

Changing the sample wasm url to a github raw reference will avoid the CORS issue, as includes `access-control-allow-origin: *`

```js
const plugin = await createPlugin(
    'https://raw.githubusercontent.com/extism/extism/main/wasm/code.wasm',
    { useWasi: true }
);
```

**Comment by nilslice** [comment]
good idea! GitHub is not consistent with this it seems... 

we should use https://modsurfer.dylibso.com instead 😎
