### ISSUE TITLE
Setup Continuous Delivery

### ISSUE THREAD

**Issue by neuronicnobody** [extism/js-sdk#13]

**Comment by chrisdickinson** [comment]
Noting here: ideally we'd publish the package to both `@extism/extism` and `extism`.

**Comment by chrisdickinson** [comment]
Left to do:
- [x] We already publish to both `@extism/extism` and `extism`
- [ ] Separate the "push tag" workflow (to build the library artifacts) from the "publish release" workflow (which should publish the library artifacts to NPM)
- [ ] Integrate the `typedoc` builds into the release (#16)

**Comment by bhelx** [comment]
I think we made some progress here but haven't come back to follow up on this issue. I feel like it's a bit too broad though. We already do have some CD, which was the original goal, so i'm going to close. Let's move the individual issues to follow ups if we need them.
