### ISSUE TITLE
Provide Helper Functions for Encoding/Decoding Input/Output

### ISSUE THREAD

**Issue by wikiwong** [extism/js-sdk#22]
Currently it's very verbose to convert raw binary to JSON. It must be decoded to a string first (unless there is a way to go directly to JSON)

example code:
```
JSON.parse((new TextDecoder).decode(vowelsCounted))
```

**Comment by chrisdickinson** [comment]
Addressed in #21!

**Comment by chrisdickinson** [comment]
Fixed by #21!
