### ISSUE TITLE
Make using deno more egonomic

### ISSUE THREAD

**Issue by sigmaSd** [extism/js-sdk#39]
Currently if I want to use deno 
```ts
import createPlugin from "https://raw.githubusercontent.com/extism/js-sdk/main/src/mod.ts";
```

I need to run like this `deno run --import-map https://raw.githubusercontent.com/extism/js-sdk/main/deno.json deno_run.ts`

You can see I had to specify the import map for the code to work

<del>I think if this was published in deno.com/x it would have picked the deno.json file automatically.</del>

**Comment by sigmaSd** [comment]
Seems like even using deno.land have the same problem, I'll keep the issue open to improve the usage with deno , because being obligated to use that import map is not convenient at all

**Comment by nilslice** [comment]
will look into this - thank you!
