### ISSUE TITLE
Examples/index.html mod.js missing

### ISSUE THREAD

**Issue by collapsinghierarchy** [extism/js-sdk#68]
I'm trying to get an extism plugin running inside a browser without node.js and albeit the index.html example is a very useful one, i cannot get it to work without the referenced mod.js. 

Could you suggest a workaround?

Edit: I have the feeling that i simply do not understand something quite crucial here. I was able to find the mod.js in the npm repository of the js-sdk module. Which is quite big: apprx. 95 kB. Is it the correct one?

**Comment by nilslice** [comment]
Hey! Are you using a JS bundler or anything and can't load the library?

Or simply just trying to create a script tag in a html file and run in the browser?

If the latter, see if this works as a starting point:

```html

<input class="input" value="..." disabled />
<br />
<img class="img" src />

<script type="module">
  const extism = await import("https://esm.sh/@extism/extism")
  const plugin = await extism.createPlugin("https://cdn.modsurfer.dylibso.com/api/v1/module/d7c54420f559239689b0b3df41ab8a692d7450120397190cb1167dc05008f633.wasm", {useWasi: false})

  const img = document.querySelector('.img');
  const input = document.querySelector('.input');
  input.disabled = false;

  const update = async (event) => {
    const text = event.target.value;
    const output = await plugin.call("handle", JSON.stringify({value: text, color: "blue", font_size: 200}));
    img.src = `data:image/png;base64,${output.json().value}`
  }

  input.addEventListener('input', update);
</script>
```

**Comment by collapsinghierarchy** [comment]
I tried the latter! The solution
` const extism = await import("https://esm.sh/@extism/extism")`
worked like a charm! I've got now a working example. I'll try the JS bundling way as well. Thank you!
