### ISSUE TITLE
install with Deno 2 runtime

### ISSUE THREAD

**Issue by adunne09** [extism/js-sdk#93]
[https://jsr.io/@extism/extism](https://jsr.io/@extism/extism) and `import createPlugin from "jsr:@extism/extism";` [here](https://github.com/extism/js-sdk?tab=readme-ov-file#getting-started) in the README indicate that there is an extism jsr package, but when I run `deno add jsr:@extism/extism`, I get:

```
error: jsr:@extism/extism was not found, but a matching npm package exists. Did you mean `deno add npm:@extism/extism`
```

Is this the intended behavior, or is there meant to be an extism jsr package?

**Comment by bhelx** [comment]
As discussed in Discord, I believe this should be a JSR package. But maybe something changed in Deno 2.

**Comment by chrisdickinson** [comment]
Hm, maybe Deno 2 isn't picking up the `rc` release?

**Comment by chrisdickinson** [comment]
Confirmed: deno 2 isn't picking up rc releases. You can work around this for now using `deno add jsr:@extism/extism@2.0.0-rc9`. (We'll cut a v2 release of the js-sdk soon.)

**Comment by G4Vi** [comment]
Closing in favor of https://github.com/extism/js-sdk/issues/96 as it's now just a documentation issue.
